### ISSUE TITLE
Compare Polkadot to other blockchain solutions

### ISSUE THREAD

**Issue by lsaether** [w3f/polkadot-wiki-old#42] opened 2019-03-12 16:53 UTC
How does Polkadot / Substrate compare to other blockchain solutions?

 - [] Polkadot vs. Ethereum (Runtime development vs. smart contracts)
 - [] Polkadot vs. Tezos (Governance comparison, VM comparison)
 - [] Polkadot vs. Cosmos (Interchain protocol comparison)

**Comment by laboon** [comment] 2019-03-15 10:44
This is a dupe of #36 .  I will add the info in the description to a comment there.

**Closed as completed by laboon** 2019-03-15 10:44 UTC
